sudo: required
services:
    - docker

before_install:
    - docker build -t kautilya20/docker-react -f dockerfile.dev .   

script:
    - docker run -e CI=true kautilya20/docker-react npm run test   